### ISSUE TITLE
No such file or directory (os error 2) nimiq-client

### ISSUE THREAD

**Issue by animanga** [nimiq/core-rs#19]

**Comment by jgraef** [comment]
Can you give us more information? What command did you run? Is that the whole output?

I suspect it's because it can't find your configuration file.

**Comment by animanga** [comment]
yes i was running cargo run command in core rust than to me file not found when i changed toolchain again other error appearing ;) one minute i post

**Comment by animanga** [comment]
warning: function is never used: `deserialize_string_vec`
   --> client/src/serialization.rs:134:1
    |
134 | / pub(crate) fn deserialize_string_vec<'de, D, T>(deserializer: D) -> Result<Vec<T>, D::Error>
135 | |     where D: Deserializer<'de>,
136 | |           T: FromStr,
137 | |           T::Err: Display {
138 | |     let values = Vec::<String>::deserialize(deserializer)?;
139 | |     values.iter().map(|value| T::from_str(value).map_err(Error::custom)).collect()
140 | | }
    | |_^
    |
    = note: #[warn(dead_code)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 1m 25s
     Running `target/debug/nimiq-client`
No such file or directory (os error 2)

**Comment by animanga** [comment]
i am trying to build and run on Ubuntu 14.04LTS plus i changed toolchain to nightly

**Comment by riptl** [comment]
@animanga core-rs targets the nightly toolchain only.
Make sure you add a configuration file before running the project: https://github.com/nimiq/core-rs#configuration

**Comment by jgraef** [comment]
You have to build with nightly. If you use rustup the easiest way is to override the toolchain in the `core-rs` directory:
```bash
rustup override set nightly
```

Alternatively tell cargo to use nightly:
```bash
cargo +nightly run
```

The issue with `No such file or directory` is because prior to our commits preparing for a beta release, the client looked for a `config.toml` in the current directory. But with the recent changes it will create an `client.example.toml` in `$HOME/.nimiq` when you first run it. You are then supposed to copy this to `client.toml` in the same directory and change the config to your needs.

The recent changes also updated the `README`, so that should be much clearer now. And the error message is much more descriptive now.

EDIT: Also that warning about `deserialize_string_vec` can be ignored.
